function panels = createPanels(rows, cols)
%CREATEPANELS Build default panel specs for a rectangular grid.

arguments
    rows (1,1) double {mustBeInteger,mustBePositive}
    cols (1,1) double {mustBeInteger,mustBePositive}
end

count = rows * cols;
template = struct( ...
    'id', 0, ...
    'row', 1, ...
    'col', 1, ...
    'rowSpan', 1, ...
    'colSpan', 1, ...
    'label', '', ...
    'labelFormat', '%s', ...
    'borderColor', [0 0 0], ...
    'borderWidth', 0.75, ...
    'innerPadding', 0.05, ...
    'sourcePath', '', ...
    'assetType', '', ...
    'importReport', '');
panels = repmat(template, 1, count);

k = 0;
for r = 1:rows
    for c = 1:cols
        k = k + 1;
        panels(k).id = k;
        panels(k).row = r;
        panels(k).col = c;
        panels(k).label = gfc.defaultLabel(k);
    end
end
end
